server:
  port: 5050

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/account_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root@39
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  # 256-bit secret key (Base64-encoded) for HS256 — must match Auth Service secret
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
